#!/usr/bin/csh
source /apps/design_environment.csh
setenv PATH "/apps/synopsys/TCAD/bin:${PATH}"
setenv PATH "/apps/synopsys/I-2013.12-SP5/bin:${PATH}"
setenv PATH "${PATH}:/apps/silvaco/bin"
setenv PATH "${PATH}:/apps/cadence/IC50/tools/perl/bin"
setenv PATH "${PATH}:/apps/cadence/SOC42/bin:/apps/SOC42/share/celtic/scripts"
setenv PATH "${PATH}:${CDS}/bin"
setenv PATH "${PATH}:${CDS_VHDL}"
setenv PATH "${PATH}:${IC}/tools/bin"
setenv PATH "${PATH}:${IC}/tools/dfII/bin"
setenv PATH "${PATH}:${IC}/tools/concice/bin"
setenv PATH "${PATH}:${IC}/tools/dracula/bin"
setenv PATH "${PATH}:${IUS}/tools/bin"
setenv PATH "${PATH}:/apps/altera8.1/quartus/bin"

setenv LD_LIBRARY_PATH /apps/synopsys/TCAD/tcad/current/linux/lib
setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${IUS}/tools/lib
setenv LD_LIBRARY_PATH ${LD_LIBRARY_PATH}:${IC}/tools/lib

setenv HSP_HOME /apps/synopsys/HSPICE/hspice
setenv VCS_HOME /apps/synopsys/I-2014.03-2
source ${VCS_HOME}/bin/environ.csh

dc_shell -f synopsys16b.script | tee synres16.txt
grep -i error synres16.txt
grep -i latch synres16.txt
grep -i violated synres16.txt
